[browser]
gatherUsageStats = false

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[theme]
base = "light"
primaryColor = "#2980B9"
secondaryBackgroundColor = "#F8F9FA"
textColor = "#2C3E50"
